### ISSUE TITLE
The `form.validate()` function only validates the first field

### ISSUE THREAD

**Issue by lmgonzalves** [spaceavocado/svelte-form#2]
Thanks a lot for this library!
It is allowing handling forms really easy in the Svelte app I'm working on :)

But, I'm having an issue. Basically it is with section [Trigger Form Validation](https://github.com/spaceavocado/svelte-form#trigger-form-validation), when I call:

```javascript
// Trigger validation of all fields
form.validate();
```

Only the first field get validated, instead of validating all fields (expected behavior).
Can you check if that is the case, or am I doing something wrong?

Thanks again, great job here!

**Comment by lmgonzalves** [comment]
Sorry, it was my bad, the library is working nicely.
I was providing an initial `value`, but not binding it properly to the `input`...
Thanks!

**Comment by davidhorak** [comment]
@lmgonzalves no worries, thanks for closing of the ticket.
